# Generated by Django 3.2.7 on 2022-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('food', models.CharField(default='', max_length=1255)),
                ('medicine', models.CharField(default='', max_length=1255)),
                ('appointment', models.CharField(default='', max_length=1255)),
                ('relatives', models.CharField(default='', max_length=1255)),
                ('healthstatus', models.CharField(default='', max_length=255)),
                ('dob', models.DateField()),
                ('allergies', models.CharField(default='', max_length=1255)),
                ('roomno', models.CharField(default='', max_length=1255)),
            ],
        ),
    ]
