# Generated by Django 3.2.7 on 2022-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
